title: Jackson Ogles - Software Engineer
email: jackson.ogles28@gmail.com
description: >-
  This website showcases my work contributions 
  and interests over the course of my career. 
  Thanks for visiting!
baseurl: "/work-website"
url: "https://cjogles.github.io/"
social_links:
  github:  cjogles
  linkedin: cjogles
theme: minima
show_excerpts: true
paginate: 3