remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Jackson Ogles]
description: [View my work contributions and interests below:]
show_downloads: [false]
google_analytics: [332391305]
